### ISSUE TITLE
Excellent work!! When will the code and dataset be released?~ 

### ISSUE THREAD

**Issue by yiyuzhuang** [Skype-line/X-Avatar#1]
Hope it is coming soon!

**Comment by zcdliuwei** [comment]
+1

**Comment by llpspark** [comment]
+1

**Comment by MoyGcc** [comment]
Thanks for your interest. Access to the data will be available before March 24, 2023 (CVPR'23 camera-ready deadline) and the code will be released before CVPR'23 which starts on June 18th.

**Comment by Skype-line** [comment]
Hi all, access to X-Humans dataset is available now [here](https://forms.gle/rHZgZnmUJnFuZUi48). Please fill in the Google form and we will contact you later.
