### ISSUE TITLE
Rendering code for meshes in X-Human

### ISSUE THREAD

**Issue by ShunyuanZheng** [Skype-line/X-Avatar#16]
Thank you for your excellent work. Could you share the code for rendering image and depth on the X-Human dataset?

**Comment by Skype-line** [comment]
Hi, thanks for your interest in our work.
I just uploaded the rendering code [here](https://github.com/Skype-line/X-Avatar/blob/main/data_process/rendering_RGBD_image.py). Hope it helps :)

**Comment by ShunyuanZheng** [comment]
> Hi, thanks for your interest in our work. I just uploaded the rendering code [here](https://github.com/Skype-line/X-Avatar/blob/main/data_process/rendering_RGBD_image.py). Hope it helps :)

Thanks!
