### ISSUE TITLE
About X-Humans Datasets

### ISSUE THREAD

**Issue by somnus1840** [Skype-line/X-Avatar#2]

**Comment by MoyGcc** [comment]
> I also applied for it, when will it be approved?

Hi, we sent you the consent form but we got automatic reply saying that your email address is no longer in use. Please re-fill the google form with a institutional and valid email address.

**Comment by MoyGcc** [comment]
Do you mean there is a Gateway Timeout error?

**Comment by JACKYLUO1991** [comment]
@MoyGcc Not really. I always got spam files before, so I changed it on purpose.

**Comment by MoyGcc** [comment]
I see. As long as you can log into the website and agree with the consent form, we will send you the download link.

**Comment by JACKYLUO1991** [comment]
@MoyGcc I received the link, but the link never clicked in.

**Comment by JACKYLUO1991** [comment]
@MoyGcc I received the link, but the link keeps showing that the click is not working.

**Comment by MoyGcc** [comment]
Can you try to copy and paste the link into your browser? The link works for me on both Safari and Chrome.
