### ISSUE TITLE
Original video of the demo gifs

### ISSUE THREAD

**Issue by mks0601** [Skype-line/X-Avatar#22]
Hi, thanks for your work.
Could you share the original RGB videos of the demo_motion_sequence (https://drive.google.com/drive/folders/1_bdGz8YHLT0ew8hNRY6ZcM_oM1ZAQChv)? Thanks!

**Comment by MoyGcc** [comment]
Hi, here are the links to the original YouTube videos:
https://www.youtube.com/watch?v=fr6bsl4J7Vc&ab_channel=KerryBar-Cohn
https://www.youtube.com/watch?v=lXJGRz1nep8&ab_channel=TennisUnleashed
https://www.youtube.com/watch?v=Ltt4dkRkSG0&ab_channel=Ti%26MeTV

We simply trimmed a short clip from these videos for our demo.

**Comment by mks0601** [comment]
Thanks for the sharing. Could you let me know exact frame indices that you used so that I can easily reuse the provided SMPL-X parameters?

**Comment by MoyGcc** [comment]
Hi, I just tried to find the videos that align with the provided SMPL-X parameters. You can find them in the same Google Drive folder as demo_motion_sequence. I didn't have time to carefully verify the alignment but it looks ok though. Hope that could be helpful.

**Comment by mks0601** [comment]
Awesome. Thanks! It seems ballet and emotion has the same number of frames, but tennis has more frames in the RGB videos. It seems early frames are not used for the demo. If you have time and can check this, that would be greatly helpful :)

**Comment by MoyGcc** [comment]
Thanks for checking the frames. I uploaded a new one for tennis. It aligns well with our demo videos so it should be the one we used in the end.

**Comment by MoyGcc** [comment]
Hi, sorry for the late reply due to the ECCV deadline! Have you already used the SMPL-X parameters to generate the animated human models? I just checked the files and the one that was uploaded to Google Drive is not the original one (probably clipped by my student). I do have the original footage (longer sequence) and the corresponding SMPL-X parameters available. If needed, I can share them via email.

**Comment by mks0601** [comment]
Hi! Thanks for your reply. Actually, I used my regressor (https://github.com/mks0601/Hand4Whole_RELEASE) and used your pose smoothing code to get smplx parameters. I found that it gives better hand poses. Thanks for providing the original videos!

**Comment by MoyGcc** [comment]
Glad to hear it! Closing this issue now. Feel free to re-open it if there are further questions.
