### ISSUE TITLE
SMPLX -scans registration 

### ISSUE THREAD

**Issue by antonyvan** [Skype-line/X-Avatar#6]
hello,
Thanks for your wonderful work. 
Is it possible to release the SMPLX and scans registration code ?  so that we can use your code in our 3d scan data
I found it is hard to get stable 3D joint estimation from multi-views of openpose 2D keypoints.
Thanks a million.

Regards

**Comment by MoyGcc** [comment]
Hi, thank you for your interest. Unfortunately, we haven't planned to release the SMPL-X registration code currently but we do consider make it public in the future. We will make an update here once we will release the registration code. Thank you for your understanding.
