### ISSUE TITLE
Run "Quick Demo", but the output has no texture

### ISSUE THREAD

**Issue by nick8592** [Skype-line/X-Avatar#7]
Hi, 
Thanks for you excellent work.
I've run the `demo.py` and successful get the output mesh `*.ply` files.

Is it possible to get the avatar **with texture** instead of only the geometry?
(By the way, I've sent out the request form for the X-Humans Dataset)

Below is the avatar that I get after running the `demo.py` with subject `00034_rgbd`.
![0034_rgbd_0000](https://github.com/Skype-line/X-Avatar/assets/56616275/eef832c2-f930-4823-b887-06cc734453d8)

**Comment by felixshing** [comment]
Hello, I would like to ask what GPU are you using? I am using 3080 but it shows "out of memory"

**Comment by nick8592** [comment]
> Thanks! Could you please let me know what parts you did the change on 4090?

Because I've encountered `CUDA error: operation not supported when calling ’cusparseCreate(handle)' on 4090 GPU`.  
So I use [#674](https://github.com/facebookresearch/pytorch3d/issues/674) provided workaround to let the code run on RTX 4090.

I replaced `code/lib/model/smpl.py` [line 268](https://github.com/Skype-line/X-Avatar/blob/abf98296efac3e899f0e6450b76161adea755305/code/lib/model/smpl.py#L268) as below 
```
x = np.linalg.inv(output['smpl_tfs'].squeeze(0).cpu())
self.tfs_c_inv = torch.tensor(x).cuda()
```
and replaced `code/lib/xavatar_basic_model.py` [line 463](https://github.com/Skype-line/X-Avatar/blob/abf98296efac3e899f0e6450b76161adea755305/code/lib/xavatar_basic_model.py#L463) as below
```
x = np.linalg.inv(grads.reshape(-1, num_dim, num_dim).cpu())
x = x.reshape(num_batch, num_points, num_dim, num_dim)
grads_inv = torch.tensor(x).cuda()
```
and `transform3d.py` in `pytorch3d` package,
replaced `return torch.inverse(self._matrix)` as below, same as [#674](https://github.com/facebookresearch/pytorch3d/issues/674) done
```
num = np.array(self._matrix.cpu())
x = np.linalg.inv(num)
return torch.tensor(x).to(self._matrix.device)
```

For me the `transform3d.py` is placed in `/root/miniconda3/envs/xavatar/lib/python3.7/site-packages/pytorch3d/transforms/`

**Comment by Skype-line** [comment]
> Hi, Thanks for you excellent work. I've run the `demo.py` and successful get the output mesh `*.ply` files.
> 
> Is it possible to get the avatar **with texture** instead of only the geometry? (By the way, I've sent out the request form for the X-Humans Dataset)
> 
> Below is the avatar that I get after running the `demo.py` with subject `00034_rgbd`. ![0034_rgbd_0000](https://user-images.githubusercontent.com/56616275/245811187-eef832c2-f930-4823-b887-06cc734453d8.png)

Hi, thanks for your interest in our work.
I ran this demo again on our GPU and it turned out to have the texture. 
I think it could be the way you visualize the results. From your screenshot, I think you are using Blender. By default, it does not show the color. Can you please change the **object interaction mode** under **layout** from "Object Mode" to "Vertex Paint"? Or you can try to visualize the results in **Meshlab** or **aitviewer** which is used in vis_meshes.py.

<img width="788" alt="Screenshot 2023-06-17 at 11 22 03" src="https://github.com/Skype-line/X-Avatar/assets/33047146/87adccf4-71ba-46ca-a4ef-b02310137d59">

**Comment by nick8592** [comment]
Thank you for your reply! The color shows up correctly. I will close this issue.

**Comment by nick8592** [comment]
Thank you for your reply! The color shows up correctly. I will close this issue.
