### ISSUE TITLE
Running demo on RTX 3080 GPU shows CUDA out of memory.

### ISSUE THREAD

**Issue by felixshing** [Skype-line/X-Avatar#8]
Hello, when I try to run the demo on RGB-D input with my 3080 GPU machine, it shows the following error

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 9.75 GiB total capacity; 8.72 GiB already allocated; 17.94 MiB free; 8.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I see in the README.md, you said if we want to train the model on 2080 Ti, we should 

> reduce either the batch size datamodule.dataloader.batch_size or the number of sampled points datamodule.processor.points_per_frame. If you want to resume training from the last checkpoint, add experiments.resume=true to the command.

But I did not find such option on the demo. Could you please let me know what modification should I do in order to run the demo and inference on 3080 GPU?

**Comment by Skype-line** [comment]
Hi, thanks for your interest in our work.
In order to run the demo and inference on 2080 Ti, you can either reduce the resolution by adding "demo.resolution=256" to the command or manually change the batch_points [here](https://github.com/Skype-line/X-Avatar/blob/da93dd66cfffe18785bcba4c0dad47682b9f4f02/code/lib/xavatar_basic_model.py#L359). See #4.

**Comment by felixshing** [comment]
Thank you for your reply. I have successfully ran the demo and generated the series of ply files. However, when I try to visualize the results via aitviewer, I got the following errors. Could you please help me find where is the error?

![image](https://github.com/Skype-line/X-Avatar/assets/61814345/43f1945c-0a96-4325-a299-dc68ca7f7ca3)


Moreover, I would like to ask, how can I get the rendering FPS of the demo?

**Comment by Skype-line** [comment]
Hi,
The error happened to us when loading too many frames but 232 seems to be not that much. Something you can try:
1. add `[::2]` at the end of this [line](https://github.com/Skype-line/X-Avatar/blob/0b6e6c76ba92496bb83e350e64483e40c9a35943/code/vis_meshes.py#L39).
2. or change the [HeadlessRender](https://github.com/Skype-line/X-Avatar/blob/0b6e6c76ba92496bb83e350e64483e40c9a35943/code/vis_meshes.py#L19) to [Viewer](https://github.com/Skype-line/X-Avatar/blob/0b6e6c76ba92496bb83e350e64483e40c9a35943/code/vis_meshes.py#L21C11-L21C17), you can visualize in aitviewer and manually expert videos as mp4 or gif. You can find some useful documentation of aitviewer [here](https://eth-ait.github.io/aitviewer/frontend.html).

For the rendering FPS, the default value is 30, the same as [playback_fps](https://github.com/Skype-line/X-Avatar/blob/0b6e6c76ba92496bb83e350e64483e40c9a35943/code/vis_meshes.py#L22). But you can freely change this variable.
