### ISSUE TITLE
Animation pkl file 

### ISSUE THREAD

**Issue by MohamedHussein736** [Skype-line/X-Avatar#9]
Hi,
Thanks again for your awesome work.
I trying to export a motion pkl file from video using PyMAFx as you suggested, However, the output pkl file is different than yours.  
---------------------------------------------------
x-avatar    |    PyMAFx output
---------------------------------------------------
(1, 72)     ---->  (1,24,3,3) body_pose
(1, 45)     ---->  (1,15,3,3) left_arm
(1, 45)     ---->  (1,15,3,3) right_arm
(1, 3)       ---->  (1,3,3) jaw_pose
(1, 10)     ---->  (1,50) facial_expression
---------------------------------------------------
How to move from PyMAFx output to x-avatar motion pkl file.

Thanks.

**Comment by Skype-line** [comment]
Hi,
I just added the [code](https://github.com/Skype-line/X-Avatar/blob/main/data_process/preprocess_PymafX_pose.py) to convert PyMAFx results to our format, which basically smooth the original outputs. Hope it helps :)

**Comment by MohamedHussein736** [comment]
Awesome, Thanks!
